### ISSUE TITLE
Sub page is added every time event fires

### ISSUE THREAD

**Issue by abachuk** [ToddThomson/jQuery-Mobile-Subpage-Widget#26] opened 2013-06-22 03:35 UTC
Every time $.mobile.changePage fires - copy sub-page is added to DOM stacking all copies on top of each other. Is there a way to check if sub page was already added to the DOM and prevent duplicates ?

**Comment by ToddThomson** [comment] 2013-06-25 16:21
The subpage widget binds to pageBeforeCreate and creates subpages only once.
Perhaps you can come up with a simple test app to show the issue happening. I'd be glad to take a look at the issue then. Would you also tell me what jqm version you are using?

**Comment by oobi** [comment] 2013-09-06 23:15
I have this issue also. I created a quick test which illustrates the problem:
http://dl.dropboxusercontent.com/u/14521800/test/index.html

It's using JQM 1.3.2, but it also occurs in 1.2.1

There is a zip file linked on the first page if you want the source, but in case that doesn't work:
http://dl.dropboxusercontent.com/u/14521800/test/test.zip
1. Click "page with sub page" to load a page with an embedded sub page. This page has the ID "sub-page-parent" just to help identify it in the DOM inspector.

> The parent page is active and the subpage is inserted into the DOM and is inactive.
1. Click "open sub page" open the sub-page embedded on the page. The sub page has the ID "subpage".

> The parent page is removed and the subpage is active
1. Close the sub page. 

> The parent page is reloaded. The subpage is not removed and there is now a duplicate subpage.
1. Click the home or back button to return to the first page

> The parent page is gone, one of the subpages is gone, but the duplicate remains in the DOM.

Under some circumstances you can get this to stack endlessly (i.e. create more and more duplicates which are never removed).

The issue seems to be  caused by the fact that the parent page gets removed from the DOM when changing page to the sub. I'm a little new to JQuery Mobile so I don't know whether that's preventable. I first tried storing a register of loaded child pages into the parent but obviously this gets zapped when the parent is removed.

**Comment by oobi** [comment] 2013-09-06 23:19
![subpages](https://f.cloud.github.com/assets/503084/1100102/bcbc9280-174a-11e3-93ca-b0e40657772e.png)

**Comment by abachuk** [comment] 2013-09-09 13:27
thanks @oobi for writing detailed description...

**Comment by ToddThomson** [comment] 2013-09-09 16:21
@oobi , @abachuk : Thank-you for reproducing this issue. I will take a look at why this is happening. Back to you soon.

**Comment by ToddThomson** [comment] 2013-09-09 19:20
The subpageRemove function checks on the data-url property for a specific format which the _createSubPage function has previously setup. When the subpage is created, in your sample, the data-url is initialized to ..&ui-page=subpage. For some reason, jQM is altering this value (the data-url property) to "subpage" when the subpage becomes the active page ( prob in jQM changePage ). This causes the parent of the subpage to be removed in error with the subpageRemove function.
I will need additional time to check why this is the case.

**Comment by oobi** [comment] 2013-09-09 22:30
Thanks for taking a look. I did a little fiddling on the off chance it helps your investigation:
- set data-url to data-subpageurl : that property persists when the subpage is created and activated so you keep your key
- With that modification, the page removal code never seems to fire - JQM must be the thing responsible for removing the parent page
- adding data-dom-cache=true to the parent page (sort of) fixes the issue of multiple dialogs being created because the parent is never removed

``` javascript
var subpageRemove = function (e, ui) {
                    var nextPage = ui.nextPage, npURL;

                    if (ui.nextPage) {
                        npURL = nextPage.jqmData("subpageurl");
                        if (npURL && npURL.indexOf( self.parentPageUrl + "&" + $.mobile.subPageUrlKey) !== 0) {
debugger; // this never fires
                            self.childPages().remove();
                            self.parentPage.remove();
                        }
                    }
                };
```

**Comment by ToddThomson** [comment] 2013-09-09 23:00
@oobi I took the sample that you provided and converted it to my testing env ( VS, MVC 4.0). Here is what I've found so far (it took a bit as I haven't looked at this code for months):
The url for the subpage needs to be of the form:

a href="#@Url.Content("~/home/subpageparent")&ui-page=test-subpage" data-role="button" data-transition="flip">Open test subpage /a

where 'test-subpage' is the id of the subpage div. Don't forget the leading hash.

I've tested this with jQM 1.2 so far and there are no issues. The link href must be of this format or jQM will not find the subpage and then will alter the data-url property of the link. If the data-url property is overwritten then the subpageRemove function will not work properly.

I'll test with the jQM 1.3 branch now..

**Comment by ToddThomson** [comment] 2013-09-09 23:07
@oobi I forgot to mention that I tested with version 1.1 of the subpage widget. This is currently the version I use in production with jQM 1.2.
I'll update to the latest GitHub version and test.

**Comment by ToddThomson** [comment] 2013-09-09 23:39
@oobi OK. I do see what the problem is now. Look for the fix tomorrow.

**Comment by oobi** [comment] 2013-09-09 23:48
I'm not sure I did it right, but that URL format causes JQM to choke for me

> unrecognized expression: #subpages.html&ui-page=subpage

I updated the demo link to that just to illustrate -- perhaps it's related to the version of jQM - I'll have a crack on 1.2 as you suggest. 

Incidentally, the demo linked from the info page (http://m.integra-international.net/home/about) exhibits the double-up behaviour on the "about" link.

**Comment by oobi** [comment] 2013-09-09 23:49
ah saw your post just after I hit submit - ok will wait for tomorrow :) 

Thanks again!

**Comment by ToddThomson** [comment] 2013-09-10 01:25
@oobi Committed new version specific subpage widgets files. Please test.

**Comment by oobi** [comment] 2013-09-10 03:50
Works nicely. 

I misunderstood your reply about the link format -- if you include a # then it doesn't work. The link URL needs to look like this:

``` html
<a href="subpages.html&ui-page=subpage" data-role="button" data-transition="flip">Open sub page</a>

not this (omit the hash):

<a href="#subpages.html&ui-page=subpage" data-role="button" data-transition="flip">Open sub page</a>
```

Thanks!

**Comment by ToddThomson** [comment] 2013-09-10 14:43
@oobi did you use the 1.3 or 1.2 version for testing?

**Closed as completed** 2013-09-10 15:07 UTC

**Comment by oobi** [comment] 2013-09-10 21:13
1.3

Chris Carey
